class Config:
    LYFT_AUTH_HEADER = 'Bearer 7qpfp4aezbRHX0KnwZvB8w1/9lwqHB2fzcBEZcOIMB6gWZyuQLGx4LEPAf1hscurLEd0xVOx8uvLxh7EkLejdUPr/HlJrlrjVQ2Q+FmqLOuMuceFjKMgTO4='
    LYFT_CLIENT_ID = 'fPqQjXzeLfin'
    LYFT_CLIENT_TOKEN = '7qpfp4aezbRHX0KnwZvB8w1/9lwqHB2fzcBEZcOIMB6gWZyuQLGx4LEPAf1hscurLEd0xVOx8uvLxh7EkLejdUPr/HlJrlrjVQ2Q+FmqLOuMuceFjKMgTO4='
    LYFT_CLIENT_SECRET = '8X-XVVj5KuW1Kw3KsJU_hWazM7qKRT44'
    GMAPS_KEY = 'AIzaSyBLQPN9GfNuA42DzGyQO7ZUdxa1NIBkw5M'
    GMAPS_ROADS_KEY = 'AIzaSyA8YcukcuUYvvXocGvngoDeJtUbRp2IYvE'
    GMAPS_PLACES_KEY = 'AIzaSyBvTEiLJjtkuh_tN89sx6S70Mkd1EddDrM'